kind: Service
apiVersion: v1
metadata:
  name: foggle
spec:
  selector:
    app: foggle
    tier: backend
  ports:
  - protocol: TCP
    port: 8070
    targetPort: 8070
    nodePort: 31070
  type: NodePort
